packages:
  - "packages/*"
  - "apps/*"

catalogMode: strict

catalogs:
  dev:
    "@biomejs/biome": ^1.5.3
    "@types/bun": latest
    "@types/express": ^5.0.0
    "@types/node": ^24.10.1
    "@types/treeify": ^1.0.3
    "@typescript/native-preview": ^7.0.0-dev.20251120.1
    msw: ^2.10.4
    publint: ^0.3.15
    tsdown: ^0.15.1
    unplugin-unused: ^0.5.6
    vitest: ^3.2.4
    vitest-mock-extended: ^3.1.0

  peer:
    "@faker-js/faker": ^10.0.0
    gunshi: ^0.26.3
    chalk: ^5.6.2
    ora: ^8.2.0
    treeify: ^1.1.0

  prod:
    "@1password/connect": ^1.4.2
    "@anthropic-ai/claude-code": ^1.0.109
    "@linear/sdk": ^55.0.0
    "@modelcontextprotocol/sdk": ^1.18.0
    "@orama/orama": ^3.1.11
    express: ^4.21.2
    modal: ^0.3.19
    node-html-parser: ^7.0.1
    openai: ^5.12.1
    winston: ^3.17.0
    zod: ^3.25

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - msw
  - protobufjs

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
